version: '3'
services:
  simple-web-event-tracking:
    image: simple-web-event-tracking
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
      - DB_NAME=simple-web-event-tracking
      - PYTHONDONTWRITEBYTECODE=1
  
  postgres:
    image: postgres:9.6.24-alpine3.15
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: simple-web-event-tracking
  
  nginx:
    image: nginx:1.21.5-alpine
    restart: unless-stopped
    ports:
      - 3001:80
    volumes:
      - ./static:/usr/share/nginx/html

volumes:
  mariadb-data:
  postgres-data:
